#@ load("@ytt:data", "data")

#@ def stripslash(n):
#@  return n.replace("/","-")
#@ end

resources:

#@ for distro in data.values.distros :
  - name: #@ stripslash("blueprints-" + distro.name)
    type: git
    icon: github
    source:
      uri: #@ data.values.git_uri
      branch: main
      paths:
        - #@ "docker/" + distro.name + "/*"
  - name: #@ stripslash("harbor-slot-" + distro.name)
    type: registry-image
    icon: docker
    source:
      repository: #@ data.values.registry_repo
      username: ((docker-registry-username))
      password: ((docker-registry-password))
      tag: #@ distro.name
#@ end

jobs:
#@ for distro in data.values.distros :
#@   for arch in distro.arch :
  - name: #@ stripslash("build-" + distro.name + "-" + arch)
    serial_groups: [ build-image ]
    plan:
      - get: #@ "blueprints-" + distro.name
        trigger: true
      - task: docker-build
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: concourse/oci-build-task
          inputs:
            - name: #@ stripslash("blueprints-" + distro.name)
          caches:
            - path: cache
          outputs:
            - name: image
          run:
            path: build
          params:
            CONTEXT: #@ "blueprints-" + distro.name + "/docker/" + distro.name
            IMAGE_PLATFORM: #@ arch
        output_mapping:
          image: pikefarm-workers-image
      - put: #@ stripslash("harbor-slot-" + distro.name)
        params:
          image: pikefarm-workers-image/image.tar
#@  end
#@ end
