#@ load("@ytt:data", "data")

resources:

#@ for distro in data.values.distros :
  - name: #@ "blueprints-" + distro.name
    type: git
    icon: github
    source:
      uri: https://github.com/bertrand-lupart/pikefarm-workers.git
      branch: main
      paths:
        - #@ "docker/" + distro.name + "/*"
  - name: #@ "harbor-slot-" + distro.name
    type: registry-image
    icon: docker
    source:
      repository: harbor.ci.gstack.io/pikelang/pikefarm-workers
      username: ((docker-registry-username))
      password: ((docker-registry-password))
      tag: #@ distro.name
#@ end

jobs:
#@ for distro in data.values.distros :
#@   for arch in distro.arch :
  - name: #@ "build-" + distro.name + "-" + arch
    plan:
      - get: #@ "blueprints-" + distro.name
        trigger: true
      - task: docker-build
        privileged: true
        config:
          platform: linux
          inputs:
            - name: #@ "blueprints-" + distro.name
          outputs:
            - name: image
          image_resource:
            type: registry-image
            source:
              repository: concourse/oci-build-task
          run:
            path: build
          params:
            CONTEXT: #@ "blueprints-" + distro.name + "/docker/" + distro.name
            IMAGE_PLATFORM: #@ "linux/"+arch
        output_mapping:
          image: pikefarm-workers-image
      - put: #@ "harbor-slot-" + distro.name
        params:
          image: pikefarm-workers-image/image.tar
#@  end
#@ end
