name: Build and Push image
on:
  push:
    branches:
      - main
    paths:
      - 'docker/**'
jobs:
  Build-Push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
      - name: Run script
        run: |
          cd ${{ github.workspace }}
          ./build-push-docker.sh
